// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChG9cAoRNDb9_ly1rXsHnnUtfgj4gKFL8',
    appId: '1:1065114948459:web:c5c595be1df520798ef22e',
    messagingSenderId: '1065114948459',
    projectId: 'skincare-ce821',
    authDomain: 'skincare-ce821.firebaseapp.com',
    storageBucket: 'skincare-ce821.appspot.com',
    measurementId: 'G-86L8C87BRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJEfoLhLvlYuKXRFD5mOakuwmFSKAfSD8',
    appId: '1:1065114948459:android:2e6fd8dd725ea1e28ef22e',
    messagingSenderId: '1065114948459',
    projectId: 'skincare-ce821',
    storageBucket: 'skincare-ce821.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6-t-XZ5Oe3u11T7IzqXNgMoKWoJW2Dc',
    appId: '1:1065114948459:ios:cfbe7acaab8d71f18ef22e',
    messagingSenderId: '1065114948459',
    projectId: 'skincare-ce821',
    storageBucket: 'skincare-ce821.appspot.com',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS6-t-XZ5Oe3u11T7IzqXNgMoKWoJW2Dc',
    appId: '1:1065114948459:ios:cfbe7acaab8d71f18ef22e',
    messagingSenderId: '1065114948459',
    projectId: 'skincare-ce821',
    storageBucket: 'skincare-ce821.appspot.com',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChG9cAoRNDb9_ly1rXsHnnUtfgj4gKFL8',
    appId: '1:1065114948459:web:67ffbc1554c9d5088ef22e',
    messagingSenderId: '1065114948459',
    projectId: 'skincare-ce821',
    authDomain: 'skincare-ce821.firebaseapp.com',
    storageBucket: 'skincare-ce821.appspot.com',
    measurementId: 'G-JF4FPKSYKE',
  );
}
